/** IANA 时区 + 中文展示名（value 仍为标准 IANA，供接口校验与后续真太阳时等逻辑使用） */
export type TimezoneOptionZh = { iana: string; labelZh: string };

export const TIMEZONE_OPTIONS_ZH: TimezoneOptionZh[] = [
  { iana: "Asia/Shanghai", labelZh: "中国 · 北京时间（东八区）" },
  { iana: "Asia/Urumqi", labelZh: "中国 · 乌鲁木齐（新疆，UTC+6）" },
  { iana: "Asia/Hong_Kong", labelZh: "中国香港" },
  { iana: "Asia/Macau", labelZh: "中国澳门" },
  { iana: "Asia/Taipei", labelZh: "中国台湾" },
  { iana: "Asia/Tokyo", labelZh: "日本 · 东京" },
  { iana: "Asia/Seoul", labelZh: "韩国 · 首尔" },
  { iana: "Asia/Singapore", labelZh: "新加坡" },
  { iana: "Asia/Bangkok", labelZh: "泰国 · 曼谷" },
  { iana: "Asia/Jakarta", labelZh: "印度尼西亚 · 雅加达" },
  { iana: "Asia/Manila", labelZh: "菲律宾 · 马尼拉" },
  { iana: "Asia/Kuala_Lumpur", labelZh: "马来西亚 · 吉隆坡" },
  { iana: "Asia/Ho_Chi_Minh", labelZh: "越南 · 胡志明市" },
  { iana: "Asia/Dubai", labelZh: "阿联酋 · 迪拜" },
  { iana: "Asia/Kolkata", labelZh: "印度 · 加尔各答" },
  { iana: "Asia/Kathmandu", labelZh: "尼泊尔 · 加德满都" },
  { iana: "Asia/Colombo", labelZh: "斯里兰卡 · 科伦坡" },
  { iana: "Asia/Dhaka", labelZh: "孟加拉 · 达卡" },
  { iana: "Asia/Yangon", labelZh: "缅甸 · 仰光" },
  { iana: "Asia/Tashkent", labelZh: "乌兹别克斯坦 · 塔什干" },
  { iana: "Asia/Almaty", labelZh: "哈萨克斯坦 · 阿拉木图" },
  { iana: "Asia/Riyadh", labelZh: "沙特阿拉伯 · 利雅得" },
  { iana: "Asia/Tehran", labelZh: "伊朗 · 德黑兰" },
  { iana: "Asia/Jerusalem", labelZh: "以色列 · 耶路撒冷" },
  { iana: "Europe/London", labelZh: "英国 · 伦敦" },
  { iana: "Europe/Paris", labelZh: "法国 · 巴黎" },
  { iana: "Europe/Berlin", labelZh: "德国 · 柏林" },
  { iana: "Europe/Rome", labelZh: "意大利 · 罗马" },
  { iana: "Europe/Madrid", labelZh: "西班牙 · 马德里" },
  { iana: "Europe/Amsterdam", labelZh: "荷兰 · 阿姆斯特丹" },
  { iana: "Europe/Moscow", labelZh: "俄罗斯 · 莫斯科" },
  { iana: "America/New_York", labelZh: "美国 · 东部（纽约）" },
  { iana: "America/Chicago", labelZh: "美国 · 中部（芝加哥）" },
  { iana: "America/Denver", labelZh: "美国 · 山地（丹佛）" },
  { iana: "America/Los_Angeles", labelZh: "美国 · 太平洋（洛杉矶）" },
  { iana: "America/Anchorage", labelZh: "美国 · 阿拉斯加" },
  { iana: "Pacific/Honolulu", labelZh: "美国 · 夏威夷" },
  { iana: "America/Toronto", labelZh: "加拿大 · 多伦多" },
  { iana: "America/Vancouver", labelZh: "加拿大 · 温哥华" },
  { iana: "America/Sao_Paulo", labelZh: "巴西 · 圣保罗" },
  { iana: "America/Mexico_City", labelZh: "墨西哥 · 墨西哥城" },
  { iana: "Australia/Sydney", labelZh: "澳大利亚 · 悉尼" },
  { iana: "Australia/Melbourne", labelZh: "澳大利亚 · 墨尔本" },
  { iana: "Pacific/Auckland", labelZh: "新西兰 · 奥克兰" },
  { iana: "UTC", labelZh: "协调世界时（UTC）" },
];
